// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dliraqojtoudabanwrbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsaXJhcW9qdG91ZGFiYW53cmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDA3NTYsImV4cCI6MjA3MTg3Njc1Nn0.VJF1scuLB89tZlZl-1CpY6WlGdnFD6utvP7K1ZV97mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});